# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

jobs:
- job: Batchsample
  steps:
  - script: |
      cd Excel-custom-functions/Batching
      npm install
      npm run build
    displayName: 'npm install and build'

- job: Storagesample
  steps:
  - script: |
      cd Excel-custom-functions/Batching
      npm install
      npm run build
    displayName: 'npm install and build'
